# This file was generated by GoReleaser. DO NOT EDIT.
cask "daemonset-node-viewer" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:           ["-dr", "com.apple.quarantine", "{{staged_path}}/daemonset-node-viewer"],
          writable_paths: ["daemonset-node-viewer"]
    end
  end

  version "0.1.0-rc5"

  on_macos do
    on_arm do
      sha256 "f38ace4d7c92f6ffd5b8e1fc78835a82874d06b8f939c06dca554fd504279d21"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd41fada92e0048e3dbdbd12fcbe27b0d293305fed7b981cf4c3be10817fa773"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "701765458090b8b175865568b8f17a828e97ac60339357cc633c2898d3fd05d4"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cd413aeea1627963041083c13844ce35bfe6a393415024688d501160f68fe770"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "daemonset-node-viewer"
  desc "Visualize node resources allocated by Kubernetes DaemonSet pods"
  homepage "https://github.com/oliviermichaelis/daemonset-node-viewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daemonset-node-viewer"

  # No zap stanza required
end
