# This file was generated by GoReleaser. DO NOT EDIT.
cask "daemonset-node-viewer" do
  version "0.1.0-rc3"

  on_macos do
    on_arm do
      sha256 "e913f1333661c5b3cac818ab58c4fc4a3bfc65315e19e3c0495f2e8297915100"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4f1718730aac3d8aed6e998c35bd83a952c07cd809ec7ca097ecf6c6c61d8a4d"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77ca2d9faabc2191c0d71a35653c707aaba432a69b4956867b7b2763e6433774"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2fc97c19c1ac8b77a627b3177dda24352f7b44c20151f98b7d4ba54363130f09"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "daemonset-node-viewer"
  desc "TUI tool to visualize the proportion of Kubernetes node resources allocated by DaemonSet pods"
  homepage "https://github.com/oliviermichaelis/daemonset-node-viewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daemonset-node-viewer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/daemonset-node-viewer"]
    end
  end

  # No zap stanza required
end
