# This file was generated by GoReleaser. DO NOT EDIT.
cask "daemonset-node-viewer" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "58ee235f36af8e5d7578a1105444c3f1d63fd50b057d4cd67065a6235c46ebc1"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb9a9507b9a7d953ac01dfbdbedc0c920d5b4b5b4e9c069b0946b9687b156c60"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ec6495172cdf4dbc84b3a735c677954c75049e17f46ad93517b33f506ad7e28c"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9b9b43cf6bdf3b44c6e1b3281b73d6f292fe1dcf98c1a8fc75ed219ece19b36"
      url "https://github.com/oliviermichaelis/daemonset-node-viewer/releases/download/v#{version}/daemonset-node-viewer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "daemonset-node-viewer"
  desc "Visualize node resources allocated by Kubernetes DaemonSet pods"
  homepage "https://github.com/oliviermichaelis/daemonset-node-viewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daemonset-node-viewer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/daemonset-node-viewer"]
    end
  end

  # No zap stanza required
end
